#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPORT_DIR="$ROOT_DIR/reports"

if ! git -C "$ROOT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "ERROR: project root is not a Git checkout: $ROOT_DIR" >&2
  exit 1
fi
if [[ ! -d "$REPORT_DIR" ]]; then
  echo "ERROR: project reports directory is missing: $REPORT_DIR" >&2
  exit 1
fi

ACTIVE_BRANCH="$(git -C "$ROOT_DIR" branch --show-current)"
ACTIVE_HEAD="$(git -C "$ROOT_DIR" rev-parse --short HEAD)"
ACTIVE_UPSTREAM="$(git -C "$ROOT_DIR" rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || echo 'MISSING_UPSTREAM')"
GIT_STATUS="$(git -C "$ROOT_DIR" status --short)"
if [[ -n "$GIT_STATUS" ]]; then
  WORKING_TREE_CHANGES="$(printf '%s\n' "$GIT_STATUS" | wc -l | tr -d ' ')"
else
  WORKING_TREE_CHANGES=0
fi

printf 'workspace_root=%s\n' "$ROOT_DIR"
printf 'active_branch=%s\n' "${ACTIVE_BRANCH:-DETACHED}"
printf 'active_head=%s\n' "$ACTIVE_HEAD"
printf 'upstream=%s\n' "$ACTIVE_UPSTREAM"
printf 'working_tree_changes=%s\n' "$WORKING_TREE_CHANGES"

cat > "$REPORT_DIR/workspace_alignment_status.md" <<EOF
# Workspace Alignment Status

Generated by \`scripts/ops/validate_workspace.sh\`.

- Project root: \`$ROOT_DIR\`
- Git branch: \`${ACTIVE_BRANCH:-DETACHED}\`
- Git commit: \`$ACTIVE_HEAD\`
- Upstream: \`$ACTIVE_UPSTREAM\`
- Working tree changes: $(if [[ -n "$GIT_STATUS" ]]; then echo "present; inspect with \`git status\`"; else echo "none"; fi)
- Credential values inspected: **NO**
- External services contacted: **NO**

This check validates only the local workspace identity. It does not establish
credential readiness, release authority, market-data freshness, or trading
readiness.
EOF

printf 'workspace_alignment_report=%s\n' "$REPORT_DIR/workspace_alignment_status.md"
