window.TheAveData = {
  zones: [
    {
      id: "sneaker",
      title: "Sneaker District",
      eyebrow: "Zone 01",
      description:
        "Footwear blocks, designer rooms, release counters, and store entrances for sneaker shops connected to their own commerce.",
      storeIds: ["shoe-store-1", "sole-lab"],
    },
    {
      id: "fashion",
      title: "Fashion Avenue",
      eyebrow: "Zone 02",
      description:
        "Hoodie walls, jacket racks, hat kiosks, and apparel rooms for brands that want their own storefront inside The Ave.",
      storeIds: ["vintage-hoodie-booth", "cut-and-sew-club"],
    },
    {
      id: "producer",
      title: "Producer Alley",
      eyebrow: "Zone 03",
      description:
        "Accessories, bundles, studio-inspired drops, vinyl textures, and product rooms built around sound culture.",
      storeIds: ["sample-crate", "mixer-bag-supply"],
    },
    {
      id: "graffiti",
      title: "Graffiti Tunnel",
      eyebrow: "Zone 04",
      description:
        "Artist collaborations, mural clues, hidden drops, and invite-only stores that unlock through campaigns.",
      storeIds: ["collab-wall", "tag-market"],
    },
    {
      id: "block",
      title: "Block Party",
      eyebrow: "Zone 05",
      description:
        "The featured release stage: live drops, event moments, partner stores, and new arrivals across The Ave.",
      storeIds: ["drop-stage", "radio-row"],
    },
  ],
  stores: [
    {
      id: "shoe-store-1",
      zoneId: "sneaker",
      name: "Shoe Store #1",
      type: "Pilot Shopify store",
      description:
        "A Version 1 mock of a merchant shoe store. Version 2 connects this storefront to real Shopify products, variants, cart, and checkout.",
      integrationId: "shoe-store-1-shopify",
      accent: "#f2c94c",
      productIds: ["late-train-low", "block-runner", "crate-digger-high"],
    },
    {
      id: "sole-lab",
      zoneId: "sneaker",
      name: "Sole Lab",
      type: "Customizer concept",
      description: "A concept store for sneaker customization, laces, patches, and limited rebuilds.",
      integrationId: "mock-future-shopify",
      accent: "#50c0b8",
      productIds: ["lace-kit"],
    },
    {
      id: "vintage-hoodie-booth",
      zoneId: "fashion",
      name: "Vintage Hoodie Booth",
      type: "Apparel merchant",
      description: "Washed fleece, tour-style graphics, heavyweight tees, and capsule racks.",
      integrationId: "mock-future-shopify",
      accent: "#d94f3d",
      productIds: ["cipher-hoodie"],
    },
    {
      id: "cut-and-sew-club",
      zoneId: "fashion",
      name: "Cut & Sew Club",
      type: "Designer room",
      description: "A boutique room for jackets, patched denim, and limited garment runs.",
      integrationId: "mock-future-shopify",
      accent: "#f4f1df",
      productIds: ["avenue-varsity"],
    },
    {
      id: "sample-crate",
      zoneId: "producer",
      name: "Sample Crate Supply",
      type: "Accessory store",
      description: "Bags, accessories, socks, jewelry, and bundle-ready add-ons.",
      integrationId: "mock-future-shopify",
      accent: "#684f9b",
      productIds: ["crate-crossbody"],
    },
    {
      id: "mixer-bag-supply",
      zoneId: "producer",
      name: "Mixer Bag Supply",
      type: "Utility gear",
      description: "Record bags, laptop sleeves, cable pouches, and travel goods for mobile creators.",
      integrationId: "mock-future-shopify",
      accent: "#6ea66d",
      productIds: ["studio-sling"],
    },
    {
      id: "collab-wall",
      zoneId: "graffiti",
      name: "The Collab Wall",
      type: "Artist drop store",
      description: "Limited artist capsules and password-protected hidden tracks.",
      integrationId: "mock-future-shopify",
      accent: "#50c0b8",
      productIds: ["mural-coach-jacket"],
    },
    {
      id: "tag-market",
      zoneId: "graffiti",
      name: "Tag Market",
      type: "Hidden release booth",
      description: "Sticker packs, art tees, and unlockable products revealed through campaign clues.",
      integrationId: "mock-future-shopify",
      accent: "#f2c94c",
      productIds: ["blackbook-tee"],
    },
    {
      id: "drop-stage",
      zoneId: "block",
      name: "Drop Stage",
      type: "Featured store",
      description: "A rotating feature slot for stores, designers, DJs, and launch events.",
      integrationId: "mock-future-shopify",
      accent: "#d94f3d",
      productIds: ["block-party-cap"],
    },
    {
      id: "radio-row",
      zoneId: "block",
      name: "Radio Row",
      type: "Event merch",
      description: "Event capsules, broadcast merch, and stage-ready new arrivals.",
      integrationId: "mock-future-shopify",
      accent: "#684f9b",
      productIds: ["afterparty-tee"],
    },
  ],
  products: [
    {
      id: "late-train-low",
      name: "Late Train Low",
      price: "$128",
      lore:
        "Built for the ride home after midnight battles: clean leather, city miles, and a sole that keeps moving.",
      color: "#f2c94c",
      sizes: ["7", "8", "9", "10", "11", "12"],
    },
    {
      id: "block-runner",
      name: "Block Runner",
      price: "$146",
      lore:
        "A fast-cut runner with concrete-gray panels, reflective tags, and a heel tab made for late drop lines.",
      color: "#d94f3d",
      sizes: ["8", "9", "10", "11"],
    },
    {
      id: "crate-digger-high",
      name: "Crate Digger High",
      price: "$158",
      lore:
        "High-top structure, vinyl-black overlays, and a gum sole for collectors who still know where the samples came from.",
      color: "#50c0b8",
      sizes: ["7", "8", "9", "10", "11", "12", "13"],
    },
    {
      id: "lace-kit",
      name: "Sole Lab Lace Kit",
      price: "$34",
      lore: "Reflective laces, metal tips, and patch tags for rebuilding a pair around your own block.",
      color: "#50c0b8",
      sizes: ["OS"],
    },
    {
      id: "cipher-hoodie",
      name: "Cipher Hoodie",
      price: "$92",
      lore: "Heavy fleece with a washed hand, corner-store receipt graphic, and sleeve hits made for late-session cyphers.",
      color: "#d94f3d",
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: "avenue-varsity",
      name: "Avenue Varsity",
      price: "$188",
      lore: "Wool-body varsity energy with patched sleeves and a back mark for the founding stores on The Ave.",
      color: "#f4f1df",
      sizes: ["S", "M", "L", "XL"],
    },
    {
      id: "crate-crossbody",
      name: "Crate Crossbody",
      price: "$76",
      lore: "A compact utility bag shaped for daily carry: headphones, wallet, sampler cards, and the next receipt.",
      color: "#684f9b",
      sizes: ["OS"],
    },
    {
      id: "studio-sling",
      name: "Studio Sling",
      price: "$84",
      lore: "Water-resistant sling with cable loops and padded pockets for the producer moving between rooms.",
      color: "#6ea66d",
      sizes: ["OS"],
    },
    {
      id: "mural-coach-jacket",
      name: "Mural Coach Jacket",
      price: "$118",
      lore: "Lightweight shell with tunnel-tag lining and a hidden inside label for limited collab runs.",
      color: "#50c0b8",
      sizes: ["S", "M", "L", "XL"],
    },
    {
      id: "blackbook-tee",
      name: "Blackbook Tee",
      price: "$48",
      lore: "A heavyweight tee with sketchbook marks, layered tags, and a print that looks better after every wash.",
      color: "#f2c94c",
      sizes: ["S", "M", "L", "XL", "XXL"],
    },
    {
      id: "block-party-cap",
      name: "Block Party Cap",
      price: "$42",
      lore: "Unstructured cap with stage-light embroidery and an underbrim mark for launch-day crews.",
      color: "#d94f3d",
      sizes: ["OS"],
    },
    {
      id: "afterparty-tee",
      name: "Afterparty Tee",
      price: "$52",
      lore: "Soft black tee with radio tower art, show flyer typography, and a back print for the final set.",
      color: "#684f9b",
      sizes: ["S", "M", "L", "XL"],
    },
  ],
  integrations: [
    {
      id: "shoe-store-1-shopify",
      platform: "Shopify",
      status: "mocked",
      label: "Shopify connection mocked for Version 1",
      catalogSource: "Version 2 Storefront API",
      checkout: "Merchant Shopify checkout in Version 2",
    },
    {
      id: "mock-future-shopify",
      platform: "Shopify",
      status: "planned",
      label: "Future Shopify-connected store",
      catalogSource: "Mock products for Version 1",
      checkout: "Checkout handoff planned for Version 2",
    },
  ],
};
